# Generated by Django 4.2.7 on 2023-12-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0002_remove_student_email_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentscore",
            name="project",
        ),
    ]
