# Generated by Django 4.2.7 on 2024-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0003_remove_studentscore_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
