# Generated by Django 4.2.7 on 2024-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0004_student_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="score",
        ),
        migrations.AddField(
            model_name="studentscore",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
