# Generated by Django 4.2.7 on 2024-02-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0014_remove_comadviser_adviser_and_more"),
        ("studentapp", "0005_remove_student_score_studentscore_score"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentScore",
        ),
    ]
