# Generated by Django 4.2.7 on 2024-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0006_delete_studentscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
