# Generated by Django 4.2.7 on 2024-04-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0007_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
