# Generated by Django 4.2.3 on 2023-11-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("document", models.CharField(max_length=300)),
                ("presentationSlide", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=20)),
                (
                    "student_id",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LecturerFreetime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freetime", models.DateTimeField()),
                (
                    "lecturer_id",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.lecturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LecturerAppAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=300)),
                (
                    "lecturer_id",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.lecturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("appointment_date_time", models.DateTimeField()),
                (
                    "lecturer_id",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.lecturer",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.student",
                    ),
                ),
            ],
        ),
    ]
