# Generated by Django 4.2.7 on 2024-05-25 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adviser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailableTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Lecturer", "Lecturer"),
                            ("Student", "Student"),
                            ("Adviser", "Adviser"),
                            ("Committee", "Committee"),
                        ],
                        default="Admin",
                        max_length=50,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="lecturerfreetime",
            name="lecturer_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_date_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="lecturer_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="lecturer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="lecturer",
            name="password",
        ),
        migrations.RemoveField(
            model_name="score",
            name="score",
        ),
        migrations.RemoveField(
            model_name="score",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.AddField(
            model_name="appointment",
            name="committee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.student",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="summary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="lecturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="maxscore",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="score",
            name="scored",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.project",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="document",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="presentationSlide",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="topic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="LecturerAppAmount",
        ),
        migrations.DeleteModel(
            name="LecturerFreetime",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="adviser",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="adviser",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.student",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.adviser",
            ),
        ),
    ]
