# Generated by Django 4.2.7 on 2024-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_adviser_availabletime_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
