# Generated by Django 4.2.3 on 2023-11-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_studentproject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="lecturer_id",
            new_name="lecturer",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="lecturerappamount",
            old_name="lecturer_id",
            new_name="lecturer",
        ),
        migrations.RenameField(
            model_name="lecturerfreetime",
            old_name="lecturer_id",
            new_name="lecturer",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="student_id",
            new_name="student",
        ),
    ]
