# Generated by Django 4.2.3 on 2023-12-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_rename_lecturer_id_appointment_lecturer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturerappamount",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="lecturerfreetime",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="score",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentproject",
            name="project",
        ),
        migrations.RemoveField(
            model_name="studentproject",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mysite.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="document",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="presentationSlide",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="topic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Lecturer",
        ),
        migrations.DeleteModel(
            name="LecturerAppAmount",
        ),
        migrations.DeleteModel(
            name="LecturerFreetime",
        ),
        migrations.DeleteModel(
            name="Score",
        ),
        migrations.DeleteModel(
            name="StudentProject",
        ),
    ]
