# Generated by Django 4.2.7 on 2023-12-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_remove_lecturerappamount_lecturer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_project",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
