# Generated by Django 4.2.7 on 2024-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Lecturer", "Lecturer"),
                    ("Student", "Student"),
                    ("Adviser", "Adviser"),
                    ("Committee", "Committee"),
                ],
                default="Admin",
                max_length=50,
            ),
        ),
    ]
