# Generated by Django 4.2.7 on 2024-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_alter_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="email",
        ),
    ]
