# Generated by Django 4.2.7 on 2024-02-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0005_remove_student_score_studentscore_score"),
        ("mysite", "0013_remove_scoreform_student_scoreform_givescore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comadviser",
            name="adviser",
        ),
        migrations.RemoveField(
            model_name="comadviser",
            name="committee",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectmanager",
            name="comadviser",
        ),
        migrations.RemoveField(
            model_name="projectmanager",
            name="student",
        ),
        migrations.RemoveField(
            model_name="result",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="scoreform",
            name="comadviser",
        ),
        migrations.RemoveField(
            model_name="scoreform",
            name="givescore",
        ),
        migrations.AddField(
            model_name="scoreform",
            name="lecturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="scoreform",
            name="maxscore",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="scoreform",
            name="scored",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="scoreform",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studentapp.student",
            ),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Comadviser",
        ),
        migrations.DeleteModel(
            name="Committee",
        ),
        migrations.DeleteModel(
            name="ProjectManager",
        ),
        migrations.DeleteModel(
            name="Result",
        ),
    ]
