# Generated by Django 4.2.7 on 2024-02-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0006_delete_studentscore"),
        ("mysite", "0014_remove_comadviser_adviser_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScoreForm",
            new_name="Score",
        ),
    ]
