# Generated by Django 4.2.7 on 2024-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0015_rename_scoreform_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabletime",
            name="timeslot",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
