# Generated by Django 4.2.7 on 2024-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0019_history_appointment_alter_history_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="appointment_timedate",
        ),
        migrations.RemoveField(
            model_name="history",
            name="student",
        ),
        migrations.AddField(
            model_name="history",
            name="action",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
