# Generated by Django 4.2.7 on 2024-04-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0020_remove_history_appointment_timedate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="history",
            name="action",
        ),
    ]
