# Generated by Django 4.2.7 on 2024-04-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0021_rename_timestamp_history_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="created_at",
        ),
    ]
