# Generated by Django 4.2.7 on 2024-04-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0022_remove_history_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="history",
            new_name="ShowAppoinment",
        ),
    ]
