# Generated by Django 4.2.7 on 2024-04-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0023_rename_history_showappoinment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShowAppoinment",
        ),
    ]
