# Generated by Django 4.2.7 on 2024-05-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0024_delete_showappoinment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.adviser",
            ),
        ),
    ]
