# Generated by Django 4.2.7 on 2024-05-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0025_appointment_adviser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
